---
- name: has bash version > 3 installed
  homebrew:
    name: bash

- name: has bash_completion.d dir
  file:
    state: directory
    path: ~/.bash_completion.d

- name: has bash_completion file
  copy:
    src: bash_completion
    dest: ~/.bash_completion

- name: has bashrc file
  copy:
    src: bashrc
    dest: ~/.bashrc

- name: has bash_profile file
  copy:
    src: bash_profile
    dest: ~/.bash_profile

- name: has new bash in shells file
  become: True
  lineinfile:
    path: /etc/shells
    line: "{{ brew_bash_executable }}"

- name: has sh changed
  command: chsh -s "{{ brew_bash_executable }}"
