---
# tasks file for roles/tui
- name: has fzf
  homebrew:
    name: fzf

- name: has fzf completion and keybindings enabled
  shell: >
    $(brew --prefix)/opt/fzf/install --key-bindings --completion --no-zsh --no-fish --no-update-rc
  args:
    creates: ~/.fzf.bash
