---
- name: has neovim
  homebrew:
    name: neovim

- name: has python client for neovim
  pip:
    name: neovim
    executable: pip3
    extra_args: --user

- name: has neovim config dir
  file:
    state: directory
    path: ~/.config/nvim

- name: has neovim config file
  copy:
    src: vimrc
    dest: ~/.config/nvim/init.vim

- name: has vim-plug dir
  file:
    path: ~/.local/share/nvim/site/autoload/
    state: directory

- name: has vim-plug
  get_url:
    dest: ~/.local/share/nvim/site/autoload/plug.vim
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: has vim pluggins installed
  shell: nvim -e -c PlugInstall -c qall!
  failed_when: false

- name: has coc-vim settings file
  copy:
    src: coc-settings.json
    dest: ~/.config/nvim/coc-settings.json

- name: has snippets directory
  file:
    path: ~/.snippets
    state: directory

- name: has js snippets
  copy:
    src: snippets
    dest: ~/.snippets/javascript.snippets

- name: has js like snippets
  copy:
    content: "extends javascript"
    dest: "~/.snippets/{{ item }}"
  with_items:
    - javascriptreact.snippets
    - typescript.snippets
    - typescriptreact.snippets
