---
- name: has tmux
  homebrew:
    name: tmux

- name: has tmux config file
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: has tmux plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    version: master

- name: have tmux plugins installed
  shell: >
    export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins" && ~/.tmux/plugins/tpm/scripts/install_plugins.sh
