---
# tasks file for roles/fonts
- name: has font repo
  homebrew_tap:
    name: homebrew/cask-fonts

# https://github.com/ansible-collections/community.general/issues/1524
- name: has profont font
  homebrew:
    install_options: cask
    name: font-profont-nerd-font
  failed_when: false
  
# https://github.com/ansible-collections/community.general/issues/1524
- name: has hermit font
  homebrew:
    install_options: cask
    name: font-hurmit-nerd-font
  failed_when: false
